name: Lint

on: [push, pull_request]

jobs:
  black-and-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Python Lint (isort/black)
        uses: wrboyce/python-lint-action@v1.0.0
