name: Lint

on: [push, pull_request]

jobs:
  python-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Python style check
        uses: bulv1ne/python-style-check@v0.3
